### ISSUE TITLE
Menu items from previous menu render in next menu

### ISSUE THREAD

**Issue by kench** [rpi-mobile/RPIMobile-Android#31]
Hi RPI mobile developers,

I was trying out the latest version of the RPI Mobile app for Android and while navigating from the Map menu to the TV menu, the Map menu items appear after a couple of seconds.

![rpi-mobilebug](https://cloud.githubusercontent.com/assets/34564/4195555/49f9592e-37c2-11e4-9f03-5809fbe7b0fb.png)

Screenshot attached.

**Comment by kench** [comment]
![Moar Repro](http://i.imgur.com/ccJvD0o.png)

**Comment by pdpiech** [comment]
After messing around with the app a bit and speaking with someone else in person that experienced this and gave a hint of tapping the back button, I have been able to reproduce the problem and I will be looking into resolving it.

To reproduce this problem, open the app. Open the "Map" fragment and select any building in the list to transition to the map.  Then open the menu drawer and select any fragment at all.  Then touch the back button.  The app will either crash or display the "Map" fragment's list in the background of the selected fragment.

**Comment by pdpiech** [comment]
This issue should now be resolved.  Please see the latest version release tagged as "v1.0.3".

**Comment by kench** [comment]
Checked it out last night.  All is well.
